name: Build Multiplataforma

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          
      - name: Instalar Dependências
        run: npm install
        
      - name: Build da Aplicação (Windows/Linux)
        if: matrix.os != 'macos-latest'
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da Aplicação (macOS Universal)
        if: matrix.os == 'macos-latest'
        run: npx electron-builder --mac --universal
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload de Artefatos
        uses: actions/upload-artifact@v4
        with:
          name: Atalaia-${{ matrix.os }}
          path: dist/
          if-no-files-found: error
